name: "dbt_workshop_vk"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_workshop_vk"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
models:
  dbt_workshop_vk:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +tags: staging
    mart:
      +materialized: view
      +tags: mart
